- name: Demo on Play variables
  hosts: all
  vars:
    URL_1: google.com
  tasks:
    - name: printing variable url
      ansible.builtin.debug:
        msg: URL == {{URL_1}}

- name: Demo on File variables
  hosts: all
  vars_files:
    - demo-vars.yml
  tasks:
    - name: printing variable from file to url
      ansible.builtin.debug:
        msg: URL == {{URL_1}}


